"""Carve a target object out of a trained 3D Gaussian splat using per-view masks.

Every Gaussian is projected into each masked view. A Gaussian scores +1 for each view
where it lands inside the object mask and -1 for each view where it lands outside; those
whose mean score exceeds `--gamma` are kept. The result is a much smaller PLY containing
(approximately) only the object.

The projection depends on `cameras.json` being in the same normalised frame as the PLY.
Generate it with `colmap_to_cameras.py` -- or let OpenSplat emit it during training -- and
never mix the two frames.
"""

import argparse
import json
import resource
import sys
import time
from pathlib import Path

import numpy as np
from PIL import Image
from plyfile import PlyData, PlyElement

MASK_EXTS = (".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff")


def load_ply(ply_path):
    plydata = PlyData.read(ply_path)
    v = plydata["vertex"]
    return {p.name: np.array(v[p.name]) for p in v.properties}


def read_ply_iteration(ply_path, default=30000):
    """Read the training iteration recorded in a splat PLY header.

    OpenSplat's `loadPly` (OpenSplat/model.cpp:729) parses the header strictly by
    position: line 1 `ply`, line 2 the format, line 3 this comment, line 4 the vertex
    count. Preserving the true iteration matters because OpenSplat resumes from it, and it
    selects the render downscale factor and SH degree.
    """
    import re
    with open(ply_path, "rb") as f:
        header = f.read(1024)
    m = re.search(rb"comment Generated by opensplat at iteration (\d+)", header)
    return int(m.group(1)) if m else default


def save_ply(gaussians, mask, out_path, iteration):
    idx = np.where(mask)[0]
    if len(idx) == 0:
        return 0
    names = list(gaussians.keys())
    vertex_data = np.zeros(len(idx), dtype=[(n, gaussians[n].dtype) for n in names])
    for n in names:
        vertex_data[n] = gaussians[n][idx]
    PlyData(
        [PlyElement.describe(vertex_data, "vertex")],
        comments=[f"Generated by opensplat at iteration {iteration}"],
    ).write(out_path)
    return len(idx)


def load_cameras_json(json_path):
    """Load supported camera JSON into pinhole world-to-camera records."""
    with open(json_path) as f:
        raw = json.load(f)

    if isinstance(raw, list):
        cameras = []
        for cam in raw:
            if {"image_name", "K", "R", "T"}.issubset(cam):
                # COLMAP writes p_cam = R @ p_world + T directly.
                K = np.asarray(cam["K"], dtype=np.float64)
                cameras.append({
                    "img_name": cam["image_name"], "w": int(cam["width"]), "h": int(cam["height"]),
                    "fx": float(K[0, 0]), "fy": float(K[1, 1]), "cx": float(K[0, 2]), "cy": float(K[1, 2]),
                    "R_wc": np.asarray(cam["R"], dtype=np.float64), "t_wc": np.asarray(cam["T"], dtype=np.float64),
                })
                continue
            # SplatSplot/OpenSplat: camera-to-world rotation and camera centre.
            R_cw = np.asarray(cam["rotation"], dtype=np.float64)
            t_w = np.asarray(cam["position"], dtype=np.float64)
            R_wc = R_cw.T
            cameras.append({
                "img_name": cam["img_name"], "w": int(cam["width"]), "h": int(cam["height"]),
                "fx": float(cam["fx"]), "fy": float(cam["fy"]),
                "cx": float(cam.get("cx", cam["width"] / 2.0)), "cy": float(cam.get("cy", cam["height"] / 2.0)),
                "R_wc": R_wc, "t_wc": -R_wc @ t_w,
            })
        return cameras

    if isinstance(raw, dict) and "frames" in raw:
        cameras = []
        for frame in raw["frames"]:
            # Nerfstudio stores OpenGL camera-to-world matrices. Convert its camera
            # axes (right, up, back) to OpenCV (right, down, forward), then invert.
            c2w_gl = np.asarray(frame["transform_matrix"], dtype=np.float64)
            c2w_cv = c2w_gl.copy()
            c2w_cv[:3, 1:3] *= -1
            world_to_camera = np.linalg.inv(c2w_cv)
            width, height = int(frame.get("w", raw["w"])), int(frame.get("h", raw["h"]))
            fx, fy = float(frame.get("fl_x", raw["fl_x"])), float(frame.get("fl_y", raw.get("fl_y", raw["fl_x"])))
            cameras.append({
                "img_name": Path(frame["file_path"]).name, "w": width, "h": height,
                "fx": fx, "fy": fy, "cx": float(frame.get("cx", raw.get("cx", width / 2))),
                "cy": float(frame.get("cy", raw.get("cy", height / 2))),
                "R_wc": world_to_camera[:3, :3], "t_wc": world_to_camera[:3, 3],
            })
        return cameras

    raise ValueError(f"Unsupported camera JSON schema in {json_path}")



def project_gaussians(xyz_world, cam):
    p_cam = (cam["R_wc"] @ xyz_world.T).T + cam["t_wc"]
    valid = p_cam[:, 2] > 0.01
    z = np.where(valid, p_cam[:, 2], 1.0)
    px = cam["fx"] * p_cam[:, 0] / z + cam["cx"]
    py = cam["fy"] * p_cam[:, 1] / z + cam["cy"]
    return px, py, valid


def find_mask(mask_dir, img_name):
    stem = Path(img_name).stem
    for ext in MASK_EXTS:
        candidate = Path(mask_dir) / (stem + ext)
        if candidate.exists():
            return np.array(Image.open(candidate).convert("L")) > 127
    return None


def accumulate_votes(xyz, cameras, mask_dir, view_num=-1):
    """+1 per view where a Gaussian lands on the object, -1 where it lands off it."""
    votes = np.zeros(len(xyz), dtype=np.float32)
    total_views = 0
    missing = []
    mismatched = []

    if view_num <= 0 or view_num >= len(cameras):
        cams_used = cameras
    else:
        cams_used = [cameras[i] for i in
                     np.linspace(0, len(cameras) - 1, view_num, dtype=int)]

    for cam in cams_used:
        mask = find_mask(mask_dir, cam["img_name"])
        if mask is None:
            missing.append(cam["img_name"])
            continue

        h, w = mask.shape
        # The pixel coordinates come from the cameras.json intrinsics, so a mask at a
        # different resolution silently shifts every vote. Refuse rather than guess.
        if (h, w) != (cam["h"], cam["w"]):
            mismatched.append(f"{cam['img_name']}: mask {w}x{h} vs camera "
                              f"{cam['w']}x{cam['h']}")
            continue

        px, py, valid = project_gaussians(xyz, cam)
        ix = np.round(px).astype(np.int32)
        iy = np.round(py).astype(np.int32)
        in_bounds = valid & (ix >= 0) & (ix < w) & (iy >= 0) & (iy < h)
        safe_ix = np.where(in_bounds, ix, 0)
        safe_iy = np.where(in_bounds, iy, 0)
        hit = mask[safe_iy, safe_ix]
        votes[in_bounds & hit] += 1.0
        votes[in_bounds & ~hit] -= 1.0
        total_views += 1

    return votes, total_views, missing, mismatched


def main():
    start_time = time.perf_counter()

    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--scene_dir", required=True,
                   help="Scene directory holding cameras.json and masks/")
    p.add_argument("--ply_in", required=True, help="Input splat PLY file")
    p.add_argument("--ply_out", required=True, help="Output cleaned PLY file")
    p.add_argument("--cameras_json", default=None,
                   help="Override the cameras.json path (default: <scene_dir>/cameras.json)")
    p.add_argument("--mask_dir", default=None,
                   help="Override the mask directory (default: <scene_dir>/masks)")
    p.add_argument("--gamma", type=float, default=0.1,
                   help="Keep Gaussians whose mean vote exceeds this (default: 0.1)")
    p.add_argument("--views", type=int, default=2,
                   help="Use only this many evenly spaced views (-1 = all)")
    args = p.parse_args()

    scene_path = Path(args.scene_dir)
    ply_path = Path(args.ply_in)
    out_path = Path(args.ply_out)
    cameras_path = Path(args.cameras_json) if args.cameras_json else scene_path / "cameras.json"
    mask_dir = Path(args.mask_dir) if args.mask_dir else scene_path / "masks"

    for label, path in (("PLY", ply_path), ("cameras.json", cameras_path),
                        ("mask directory", mask_dir)):
        if not path.exists():
            print(f"Error: {label} not found: {path}", file=sys.stderr)
            if label == "cameras.json":
                print("Hint: generate it with "
                      f"utils/colmap_to_cameras.py --scene_dir {scene_path}",
                      file=sys.stderr)
            sys.exit(1)

    out_path.parent.mkdir(parents=True, exist_ok=True)

    gaussians = load_ply(str(ply_path))
    cameras = load_cameras_json(str(cameras_path))
    xyz = np.stack([gaussians["x"], gaussians["y"], gaussians["z"]], axis=1)
    n_in = len(xyz)

    votes, total_views, missing, mismatched = accumulate_votes(
        xyz, cameras, str(mask_dir), view_num=args.views)

    if missing:
        print(f"Warning: no mask for {len(missing)} view(s), e.g. {missing[:3]}",
              file=sys.stderr)
    if mismatched:
        print(f"Error: {len(mismatched)} mask(s) do not match their camera resolution:",
              file=sys.stderr)
        for m in mismatched[:5]:
            print(f"  {m}", file=sys.stderr)
        print("Masks must be at the resolution recorded in cameras.json, otherwise every "
              "projected vote is offset. Regenerate the masks or cameras.json.",
              file=sys.stderr)
        sys.exit(1)

    if total_views == 0:
        print(f"Error: no usable views -- {mask_dir} contains no mask matching any "
              "img_name in cameras.json.", file=sys.stderr)
        sys.exit(1)

    fg_mask = (votes / float(total_views)) > args.gamma
    if not fg_mask.any():
        print(f"Error: no Gaussian survived (gamma={args.gamma}, {total_views} views). "
              "Lower --gamma or check that the masks cover the intended object.",
              file=sys.stderr)
        sys.exit(1)

    iteration = read_ply_iteration(ply_path)
    n_out = save_ply(gaussians, fg_mask, str(out_path), iteration)

    metrics = {
        "latency_seconds": time.perf_counter() - start_time,
        # ru_maxrss is the true high-water mark; RSS at exit would miss the peak.
        "peak_ram_mb": resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024.0,
        "total_views_used": total_views,
        "n_gaussians_in": n_in,
        "n_gaussians_out": n_out,
        "retention_pct": 100.0 * n_out / n_in if n_in else 0.0,
        "iteration": iteration,
    }
    print(json.dumps(metrics))


if __name__ == "__main__":
    main()
